#Defining Variables
variables:
  IMAGE_NAME: shivamrana28/hellopy
  IMAGE_TAG: 5.0.5
  AWS_HOST: ubuntu@ec2-34-239-108-217.compute-1.amazonaws.com

#Defining Stages
stages:
  - test
  - upload-to-docker
  - deploy-to-aws

#The runTests Job (Testing the Code)
runTest:
  stage: test
  image: python:3.10.0-alpine3.15
  before_script:
    - chmod 777 -R tests
    - pip install flask
  script:
    - echo "Running Unit Test..."
    - python -m unittest discover -s tests -p "testApp.py"


#The build Job (Building and Uploading Docker Image)
build:
  stage: upload-to-docker
  image: docker:28.0.0-rc.1-cli
  services:
    - docker:28.0.0-rc.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


# The deploy Job (Deploying to AWS)
deploy:
  stage: deploy-to-aws
  before_script:
    - chmod 400 $AWS_SSH_KEY
    - apt-get update &&  apt-get -y install sudo
    - sudo apt-get install snapd && sudo snap install notes
    - sudo apt-get update
  script:
    - ssh -o StrictHostKeyChecking=no -i $AWS_SSH_KEY $AWS_HOST "
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD &&
        docker run -d -p 80:5000 $IMAGE_NAME:$IMAGE_TAG"